services:
    postgres:
        image: 'postgres:15.3'
        ports:
            - '${FORWARD_POSTGRES_PORT:-5432}:5432'
        environment:
            POSTGRES_PASSWORD: postgres
        networks:
            - sonar
        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
    adminer:
        image: 'adminer:latest'
        restart: always
        ports:
            - '${FORWARD_ADMINER_PORT:-9001}:8080'
        networks:
            - sonar
        depends_on:
            - postgres
    app:
        image: 'sonarqube:25.2.0.102705-community'
        environment:
            SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
            SONAR_JDBC_USERNAME: postgres
            SONAR_JDBC_PASSWORD: postgres
            SONAR_JDBC_URL: 'jdbc:postgresql://postgres:5432/sonar'
        ports:
            - '${FORWARD_PORT:-9000}:9000'
        networks:
            - sonar
        volumes:
            - 'data:/opt/sonarqube/data'
            - 'logs:/opt/sonarqube/logs'
            - 'extensions:/opt/sonarqube/extensions'
        depends_on:
            - postgres
    scanner:
        image: 'sonarsource/sonar-scanner-cli:11.2.1.1844_7.0.2'
        command: 'tail -F /dev/null'
        platform: linux/amd64
        environment:
            SONAR_HOST_URL: 'http://app:${FORWARD_PORT:-9000}'
            SONAR_SCANNER_OPTS: '-Dsonar.projectKey=${PROJECT_KEY}'
            SONAR_TOKEN: '${PROJECT_TOKEN}'
        volumes:
            - '${PROJECT_DIRECTORY_PATH}:/usr/src'
        networks:
            - sonar
        depends_on:
            - app
    scripts:
        build:
            context: .
            dockerfile: Dockerfile.scripts
        container_name: scripts
        environment:
            APP_PORT: '${FORWARD_PORT:-9000}'
            PROJECT_KEY: '${PROJECT_KEY}'
            PROJECT_TOKEN: '${PROJECT_TOKEN}'
        volumes:
            - ./:/home
        networks:
            - sonar
        command: tail -F /dev/null
networks:
    sonar:
        driver: bridge
volumes:
    postgres-data:
        driver: local
    data:
        driver: local
    logs:
        driver: local
    extensions:
        driver: local
